site_name: 計算機言語

nav:
  - "Home": index.md
  - "講義の概要": about.md
  - "序論": pre-intro.md
  - "特徴と分類": pre-features.md
  - "構文": pre-syntax.md
  - "命令型言語": paradigm-imperative.md
  - "オブジェクト指向言語": paradigm-oo.md
  - "関数型言語": paradigm-functional.md
  - "論理型言語": paradigm-logic.md
  - "C言語": language-c.md
  - "Java言語": language-java.md

theme:
  name: material
  font:
    text: Noto
    code: Roboto Mono
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.footer
  icon:
    logo: fontawesome/solid/keyboard
    annotation: material/plus-circle
    admonition:
      bug: fontawesome/solid/question
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  favicon: assets/favicon.svg

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex: # for math
      generic: true

  - pymdownx.superfences: # flowchart
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - attr_list # image
  - md_in_html
  - def_list
  
  - pymdownx.critic # formatting
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: '#'

extra_javascript: # for math
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


_repo_url: https://github.com/kusumotolab/lecture-program-lang
_repo_name: kusumotolab/lecture-program-lang

plugins:
  - search
  - git-revision-date-localized:
      type: date

site_url: https://kusumotolab.github.io/lecture-program-lang/
